version: '3.8'

services:

  vault:
    container_name: vault
    image: vault:0.8.2
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_DEV_ROOT_TOKEN_ID: 00000000-0000-0000-0000-000000000000
      VAULT_TOKEN: 00000000-0000-0000-0000-000000000000

  vault-init:
    image: vault:0.8.2
    container_name: vault-init
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: 00000000-0000-0000-0000-000000000000
      VAULT_ADDR: http://vault:8200
    volumes:
      - ./docker-local/:/vault-scripts
    command: sh -c "chmod +x /vault-scripts/vault-init.sh; /vault-scripts/vault-init.sh"
    depends_on:
      - vault
    links:
      - vault

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: 12345

  service:
    build:
      context: .
      dockerfile: ./docker-local/Dockerfile
      args:
        - SERVICE_NAME=ervice
    container_name: service
    ports:
      - "9999:9999"
    depends_on:
      - vault
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  client:
    image: nginx
    container_name: client
    volumes:
      - ./frontend:/usr/share/nginx/html

  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - service
      - client
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"